listener 1883
protocol mqtt
listener_allow_anonymous false
password_file E:/web kepston/Website-Capstone-B-05-Backend/mosquitto/config/passwordfile

listener 9001
protocol websockets
listener_allow_anonymous false
password_file E:/web kepston/Website-Capstone-B-05-Backend/mosquitto/config/passwordfile

persistence true
persistence_location E:/web kepston/Website-Capstone-B-05-Backend/mosquitto/data/

log_dest file E:/web kepston/Website-Capstone-B-05-Backend/mosquitto/log/mosquitto.log
connection_messages true
log_type all
